// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Packet.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace google {
namespace protobuf {
class CG_LOGINDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CG_LOGIN> {
} _CG_LOGIN_default_instance_;
class GC_LOGINDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<GC_LOGIN> {
} _GC_LOGIN_default_instance_;

namespace protobuf_Packet_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, vtype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, gameversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, programversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, publicresourceversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, maxpacketid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, forceenter_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, deviceid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, devicetype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, deviceversion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, account_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, validateinfo_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, channelid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, mediachannel_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, rapidvalidatecode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedint1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedint2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedint3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedint4_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedstring1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedstring2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedstring3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedstring4_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GC_LOGIN, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GC_LOGIN, result_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CG_LOGIN)},
  { 27, -1, sizeof(GC_LOGIN)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CG_LOGIN_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_GC_LOGIN_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "Packet.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _CG_LOGIN_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _GC_LOGIN_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CG_LOGIN_default_instance_.DefaultConstruct();
  _GC_LOGIN_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\014Packet.proto\022\017google.protobuf\"\226\004\n\010CG_L"
      "OGIN\022\r\n\005vtype\030\001 \001(\005\022\023\n\013gameversion\030\002 \001(\005"
      "\022\026\n\016programversion\030\003 \001(\005\022\035\n\025publicresour"
      "ceversion\030\004 \001(\005\022\023\n\013maxpacketid\030\005 \001(\005\022\022\n\n"
      "forceenter\030\006 \001(\005\022\020\n\010deviceid\030\007 \001(\t\022\022\n\nde"
      "vicetype\030\010 \001(\t\022\025\n\rdeviceversion\030\t \001(\t\022\017\n"
      "\007account\030\n \001(\t\022\024\n\014validateinfo\030\013 \001(\t\022\021\n\t"
      "channelid\030\014 \001(\t\022\024\n\014mediachannel\030\r \001(\t\022\031\n"
      "\021rapidvalidatecode\030\016 \001(\005\022\024\n\014reservedint1"
      "\030\017 \001(\005\022\024\n\014reservedint2\030\020 \001(\005\022\024\n\014reserved"
      "int3\030\021 \001(\005\022\024\n\014reservedint4\030\022 \001(\005\022\027\n\017rese"
      "rvedstring1\030\023 \001(\t\022\027\n\017reservedstring2\030\024 \001"
      "(\t\022\027\n\017reservedstring3\030\025 \001(\t\022\027\n\017reserveds"
      "tring4\030\026 \001(\t\"\"\n\014VALIDATETYPE\022\010\n\004TEST\020\000\022\010"
      "\n\004CYOU\020\001\"\032\n\010GC_LOGIN\022\016\n\006result\030\001 \001(\005b\006pr"
      "oto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 604);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Packet.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_Packet_2eproto

const ::google::protobuf::EnumDescriptor* CG_LOGIN_VALIDATETYPE_descriptor() {
  protobuf_Packet_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Packet_2eproto::file_level_enum_descriptors[0];
}
bool CG_LOGIN_VALIDATETYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CG_LOGIN_VALIDATETYPE CG_LOGIN::TEST;
const CG_LOGIN_VALIDATETYPE CG_LOGIN::CYOU;
const CG_LOGIN_VALIDATETYPE CG_LOGIN::VALIDATETYPE_MIN;
const CG_LOGIN_VALIDATETYPE CG_LOGIN::VALIDATETYPE_MAX;
const int CG_LOGIN::VALIDATETYPE_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CG_LOGIN::kVtypeFieldNumber;
const int CG_LOGIN::kGameversionFieldNumber;
const int CG_LOGIN::kProgramversionFieldNumber;
const int CG_LOGIN::kPublicresourceversionFieldNumber;
const int CG_LOGIN::kMaxpacketidFieldNumber;
const int CG_LOGIN::kForceenterFieldNumber;
const int CG_LOGIN::kDeviceidFieldNumber;
const int CG_LOGIN::kDevicetypeFieldNumber;
const int CG_LOGIN::kDeviceversionFieldNumber;
const int CG_LOGIN::kAccountFieldNumber;
const int CG_LOGIN::kValidateinfoFieldNumber;
const int CG_LOGIN::kChannelidFieldNumber;
const int CG_LOGIN::kMediachannelFieldNumber;
const int CG_LOGIN::kRapidvalidatecodeFieldNumber;
const int CG_LOGIN::kReservedint1FieldNumber;
const int CG_LOGIN::kReservedint2FieldNumber;
const int CG_LOGIN::kReservedint3FieldNumber;
const int CG_LOGIN::kReservedint4FieldNumber;
const int CG_LOGIN::kReservedstring1FieldNumber;
const int CG_LOGIN::kReservedstring2FieldNumber;
const int CG_LOGIN::kReservedstring3FieldNumber;
const int CG_LOGIN::kReservedstring4FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CG_LOGIN::CG_LOGIN()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Packet_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.CG_LOGIN)
}
CG_LOGIN::CG_LOGIN(const CG_LOGIN& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  deviceid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.deviceid().size() > 0) {
    deviceid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deviceid_);
  }
  devicetype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.devicetype().size() > 0) {
    devicetype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.devicetype_);
  }
  deviceversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.deviceversion().size() > 0) {
    deviceversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deviceversion_);
  }
  account_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.account().size() > 0) {
    account_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_);
  }
  validateinfo_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.validateinfo().size() > 0) {
    validateinfo_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.validateinfo_);
  }
  channelid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.channelid().size() > 0) {
    channelid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channelid_);
  }
  mediachannel_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.mediachannel().size() > 0) {
    mediachannel_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mediachannel_);
  }
  reservedstring1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.reservedstring1().size() > 0) {
    reservedstring1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring1_);
  }
  reservedstring2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.reservedstring2().size() > 0) {
    reservedstring2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring2_);
  }
  reservedstring3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.reservedstring3().size() > 0) {
    reservedstring3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring3_);
  }
  reservedstring4_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.reservedstring4().size() > 0) {
    reservedstring4_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring4_);
  }
  ::memcpy(&vtype_, &from.vtype_,
    reinterpret_cast<char*>(&reservedint4_) -
    reinterpret_cast<char*>(&vtype_) + sizeof(reservedint4_));
  // @@protoc_insertion_point(copy_constructor:google.protobuf.CG_LOGIN)
}

void CG_LOGIN::SharedCtor() {
  deviceid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devicetype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deviceversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  validateinfo_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channelid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mediachannel_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring4_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&vtype_, 0, reinterpret_cast<char*>(&reservedint4_) -
    reinterpret_cast<char*>(&vtype_) + sizeof(reservedint4_));
  _cached_size_ = 0;
}

CG_LOGIN::~CG_LOGIN() {
  // @@protoc_insertion_point(destructor:google.protobuf.CG_LOGIN)
  SharedDtor();
}

void CG_LOGIN::SharedDtor() {
  deviceid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devicetype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deviceversion_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  validateinfo_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channelid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mediachannel_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring3_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring4_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CG_LOGIN::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CG_LOGIN::descriptor() {
  protobuf_Packet_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Packet_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CG_LOGIN& CG_LOGIN::default_instance() {
  protobuf_Packet_2eproto::InitDefaults();
  return *internal_default_instance();
}

CG_LOGIN* CG_LOGIN::New(::google::protobuf::Arena* arena) const {
  CG_LOGIN* n = new CG_LOGIN;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CG_LOGIN::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.CG_LOGIN)
  deviceid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devicetype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deviceversion_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  validateinfo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channelid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mediachannel_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring4_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&vtype_, 0, reinterpret_cast<char*>(&reservedint4_) -
    reinterpret_cast<char*>(&vtype_) + sizeof(reservedint4_));
}

bool CG_LOGIN::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.CG_LOGIN)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 vtype = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &vtype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 gameversion = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &gameversion_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 programversion = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &programversion_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 publicresourceversion = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &publicresourceversion_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 maxpacketid = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &maxpacketid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 forceenter = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &forceenter_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string deviceid = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deviceid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->deviceid().data(), this->deviceid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.deviceid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string devicetype = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_devicetype()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->devicetype().data(), this->devicetype().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.devicetype"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string deviceversion = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deviceversion()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->deviceversion().data(), this->deviceversion().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.deviceversion"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string account = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_account()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->account().data(), this->account().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.account"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string validateinfo = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_validateinfo()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->validateinfo().data(), this->validateinfo().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.validateinfo"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string channelid = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_channelid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->channelid().data(), this->channelid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.channelid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string mediachannel = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mediachannel()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->mediachannel().data(), this->mediachannel().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.mediachannel"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 rapidvalidatecode = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(112u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rapidvalidatecode_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 reservedint1 = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(120u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reservedint1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 reservedint2 = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(128u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reservedint2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 reservedint3 = 17;
      case 17: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(136u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reservedint3_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 reservedint4 = 18;
      case 18: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(144u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reservedint4_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string reservedstring1 = 19;
      case 19: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(154u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reservedstring1()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->reservedstring1().data(), this->reservedstring1().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.reservedstring1"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string reservedstring2 = 20;
      case 20: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(162u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reservedstring2()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->reservedstring2().data(), this->reservedstring2().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.reservedstring2"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string reservedstring3 = 21;
      case 21: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(170u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reservedstring3()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->reservedstring3().data(), this->reservedstring3().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.reservedstring3"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string reservedstring4 = 22;
      case 22: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(178u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reservedstring4()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->reservedstring4().data(), this->reservedstring4().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.reservedstring4"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.CG_LOGIN)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.CG_LOGIN)
  return false;
#undef DO_
}

void CG_LOGIN::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.CG_LOGIN)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 vtype = 1;
  if (this->vtype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->vtype(), output);
  }

  // int32 gameversion = 2;
  if (this->gameversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->gameversion(), output);
  }

  // int32 programversion = 3;
  if (this->programversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->programversion(), output);
  }

  // int32 publicresourceversion = 4;
  if (this->publicresourceversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->publicresourceversion(), output);
  }

  // int32 maxpacketid = 5;
  if (this->maxpacketid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->maxpacketid(), output);
  }

  // int32 forceenter = 6;
  if (this->forceenter() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->forceenter(), output);
  }

  // string deviceid = 7;
  if (this->deviceid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deviceid().data(), this->deviceid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.deviceid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->deviceid(), output);
  }

  // string devicetype = 8;
  if (this->devicetype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->devicetype().data(), this->devicetype().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.devicetype");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->devicetype(), output);
  }

  // string deviceversion = 9;
  if (this->deviceversion().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deviceversion().data(), this->deviceversion().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.deviceversion");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->deviceversion(), output);
  }

  // string account = 10;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), this->account().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.account");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->account(), output);
  }

  // string validateinfo = 11;
  if (this->validateinfo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->validateinfo().data(), this->validateinfo().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.validateinfo");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->validateinfo(), output);
  }

  // string channelid = 12;
  if (this->channelid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channelid().data(), this->channelid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.channelid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->channelid(), output);
  }

  // string mediachannel = 13;
  if (this->mediachannel().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mediachannel().data(), this->mediachannel().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.mediachannel");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      13, this->mediachannel(), output);
  }

  // int32 rapidvalidatecode = 14;
  if (this->rapidvalidatecode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(14, this->rapidvalidatecode(), output);
  }

  // int32 reservedint1 = 15;
  if (this->reservedint1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(15, this->reservedint1(), output);
  }

  // int32 reservedint2 = 16;
  if (this->reservedint2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(16, this->reservedint2(), output);
  }

  // int32 reservedint3 = 17;
  if (this->reservedint3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(17, this->reservedint3(), output);
  }

  // int32 reservedint4 = 18;
  if (this->reservedint4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(18, this->reservedint4(), output);
  }

  // string reservedstring1 = 19;
  if (this->reservedstring1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring1().data(), this->reservedstring1().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      19, this->reservedstring1(), output);
  }

  // string reservedstring2 = 20;
  if (this->reservedstring2().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring2().data(), this->reservedstring2().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      20, this->reservedstring2(), output);
  }

  // string reservedstring3 = 21;
  if (this->reservedstring3().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring3().data(), this->reservedstring3().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring3");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      21, this->reservedstring3(), output);
  }

  // string reservedstring4 = 22;
  if (this->reservedstring4().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring4().data(), this->reservedstring4().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring4");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      22, this->reservedstring4(), output);
  }

  // @@protoc_insertion_point(serialize_end:google.protobuf.CG_LOGIN)
}

::google::protobuf::uint8* CG_LOGIN::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.CG_LOGIN)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 vtype = 1;
  if (this->vtype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->vtype(), target);
  }

  // int32 gameversion = 2;
  if (this->gameversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->gameversion(), target);
  }

  // int32 programversion = 3;
  if (this->programversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->programversion(), target);
  }

  // int32 publicresourceversion = 4;
  if (this->publicresourceversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->publicresourceversion(), target);
  }

  // int32 maxpacketid = 5;
  if (this->maxpacketid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->maxpacketid(), target);
  }

  // int32 forceenter = 6;
  if (this->forceenter() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->forceenter(), target);
  }

  // string deviceid = 7;
  if (this->deviceid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deviceid().data(), this->deviceid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.deviceid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->deviceid(), target);
  }

  // string devicetype = 8;
  if (this->devicetype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->devicetype().data(), this->devicetype().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.devicetype");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->devicetype(), target);
  }

  // string deviceversion = 9;
  if (this->deviceversion().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deviceversion().data(), this->deviceversion().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.deviceversion");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->deviceversion(), target);
  }

  // string account = 10;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), this->account().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.account");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->account(), target);
  }

  // string validateinfo = 11;
  if (this->validateinfo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->validateinfo().data(), this->validateinfo().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.validateinfo");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->validateinfo(), target);
  }

  // string channelid = 12;
  if (this->channelid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channelid().data(), this->channelid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.channelid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->channelid(), target);
  }

  // string mediachannel = 13;
  if (this->mediachannel().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mediachannel().data(), this->mediachannel().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.mediachannel");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        13, this->mediachannel(), target);
  }

  // int32 rapidvalidatecode = 14;
  if (this->rapidvalidatecode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(14, this->rapidvalidatecode(), target);
  }

  // int32 reservedint1 = 15;
  if (this->reservedint1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(15, this->reservedint1(), target);
  }

  // int32 reservedint2 = 16;
  if (this->reservedint2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(16, this->reservedint2(), target);
  }

  // int32 reservedint3 = 17;
  if (this->reservedint3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(17, this->reservedint3(), target);
  }

  // int32 reservedint4 = 18;
  if (this->reservedint4() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(18, this->reservedint4(), target);
  }

  // string reservedstring1 = 19;
  if (this->reservedstring1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring1().data(), this->reservedstring1().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        19, this->reservedstring1(), target);
  }

  // string reservedstring2 = 20;
  if (this->reservedstring2().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring2().data(), this->reservedstring2().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        20, this->reservedstring2(), target);
  }

  // string reservedstring3 = 21;
  if (this->reservedstring3().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring3().data(), this->reservedstring3().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring3");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        21, this->reservedstring3(), target);
  }

  // string reservedstring4 = 22;
  if (this->reservedstring4().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring4().data(), this->reservedstring4().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring4");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        22, this->reservedstring4(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.CG_LOGIN)
  return target;
}

size_t CG_LOGIN::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.CG_LOGIN)
  size_t total_size = 0;

  // string deviceid = 7;
  if (this->deviceid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->deviceid());
  }

  // string devicetype = 8;
  if (this->devicetype().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->devicetype());
  }

  // string deviceversion = 9;
  if (this->deviceversion().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->deviceversion());
  }

  // string account = 10;
  if (this->account().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account());
  }

  // string validateinfo = 11;
  if (this->validateinfo().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->validateinfo());
  }

  // string channelid = 12;
  if (this->channelid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->channelid());
  }

  // string mediachannel = 13;
  if (this->mediachannel().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mediachannel());
  }

  // string reservedstring1 = 19;
  if (this->reservedstring1().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reservedstring1());
  }

  // string reservedstring2 = 20;
  if (this->reservedstring2().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reservedstring2());
  }

  // string reservedstring3 = 21;
  if (this->reservedstring3().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reservedstring3());
  }

  // string reservedstring4 = 22;
  if (this->reservedstring4().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reservedstring4());
  }

  // int32 vtype = 1;
  if (this->vtype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->vtype());
  }

  // int32 gameversion = 2;
  if (this->gameversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->gameversion());
  }

  // int32 programversion = 3;
  if (this->programversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->programversion());
  }

  // int32 publicresourceversion = 4;
  if (this->publicresourceversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->publicresourceversion());
  }

  // int32 maxpacketid = 5;
  if (this->maxpacketid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->maxpacketid());
  }

  // int32 forceenter = 6;
  if (this->forceenter() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->forceenter());
  }

  // int32 rapidvalidatecode = 14;
  if (this->rapidvalidatecode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rapidvalidatecode());
  }

  // int32 reservedint1 = 15;
  if (this->reservedint1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reservedint1());
  }

  // int32 reservedint2 = 16;
  if (this->reservedint2() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reservedint2());
  }

  // int32 reservedint3 = 17;
  if (this->reservedint3() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reservedint3());
  }

  // int32 reservedint4 = 18;
  if (this->reservedint4() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reservedint4());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CG_LOGIN::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.CG_LOGIN)
  GOOGLE_DCHECK_NE(&from, this);
  const CG_LOGIN* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CG_LOGIN>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.CG_LOGIN)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.CG_LOGIN)
    MergeFrom(*source);
  }
}

void CG_LOGIN::MergeFrom(const CG_LOGIN& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.CG_LOGIN)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.deviceid().size() > 0) {

    deviceid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deviceid_);
  }
  if (from.devicetype().size() > 0) {

    devicetype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.devicetype_);
  }
  if (from.deviceversion().size() > 0) {

    deviceversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deviceversion_);
  }
  if (from.account().size() > 0) {

    account_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_);
  }
  if (from.validateinfo().size() > 0) {

    validateinfo_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.validateinfo_);
  }
  if (from.channelid().size() > 0) {

    channelid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channelid_);
  }
  if (from.mediachannel().size() > 0) {

    mediachannel_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mediachannel_);
  }
  if (from.reservedstring1().size() > 0) {

    reservedstring1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring1_);
  }
  if (from.reservedstring2().size() > 0) {

    reservedstring2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring2_);
  }
  if (from.reservedstring3().size() > 0) {

    reservedstring3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring3_);
  }
  if (from.reservedstring4().size() > 0) {

    reservedstring4_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring4_);
  }
  if (from.vtype() != 0) {
    set_vtype(from.vtype());
  }
  if (from.gameversion() != 0) {
    set_gameversion(from.gameversion());
  }
  if (from.programversion() != 0) {
    set_programversion(from.programversion());
  }
  if (from.publicresourceversion() != 0) {
    set_publicresourceversion(from.publicresourceversion());
  }
  if (from.maxpacketid() != 0) {
    set_maxpacketid(from.maxpacketid());
  }
  if (from.forceenter() != 0) {
    set_forceenter(from.forceenter());
  }
  if (from.rapidvalidatecode() != 0) {
    set_rapidvalidatecode(from.rapidvalidatecode());
  }
  if (from.reservedint1() != 0) {
    set_reservedint1(from.reservedint1());
  }
  if (from.reservedint2() != 0) {
    set_reservedint2(from.reservedint2());
  }
  if (from.reservedint3() != 0) {
    set_reservedint3(from.reservedint3());
  }
  if (from.reservedint4() != 0) {
    set_reservedint4(from.reservedint4());
  }
}

void CG_LOGIN::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.CG_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CG_LOGIN::CopyFrom(const CG_LOGIN& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.CG_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CG_LOGIN::IsInitialized() const {
  return true;
}

void CG_LOGIN::Swap(CG_LOGIN* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CG_LOGIN::InternalSwap(CG_LOGIN* other) {
  deviceid_.Swap(&other->deviceid_);
  devicetype_.Swap(&other->devicetype_);
  deviceversion_.Swap(&other->deviceversion_);
  account_.Swap(&other->account_);
  validateinfo_.Swap(&other->validateinfo_);
  channelid_.Swap(&other->channelid_);
  mediachannel_.Swap(&other->mediachannel_);
  reservedstring1_.Swap(&other->reservedstring1_);
  reservedstring2_.Swap(&other->reservedstring2_);
  reservedstring3_.Swap(&other->reservedstring3_);
  reservedstring4_.Swap(&other->reservedstring4_);
  std::swap(vtype_, other->vtype_);
  std::swap(gameversion_, other->gameversion_);
  std::swap(programversion_, other->programversion_);
  std::swap(publicresourceversion_, other->publicresourceversion_);
  std::swap(maxpacketid_, other->maxpacketid_);
  std::swap(forceenter_, other->forceenter_);
  std::swap(rapidvalidatecode_, other->rapidvalidatecode_);
  std::swap(reservedint1_, other->reservedint1_);
  std::swap(reservedint2_, other->reservedint2_);
  std::swap(reservedint3_, other->reservedint3_);
  std::swap(reservedint4_, other->reservedint4_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CG_LOGIN::GetMetadata() const {
  protobuf_Packet_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Packet_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CG_LOGIN

// int32 vtype = 1;
void CG_LOGIN::clear_vtype() {
  vtype_ = 0;
}
::google::protobuf::int32 CG_LOGIN::vtype() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.vtype)
  return vtype_;
}
void CG_LOGIN::set_vtype(::google::protobuf::int32 value) {
  
  vtype_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.vtype)
}

// int32 gameversion = 2;
void CG_LOGIN::clear_gameversion() {
  gameversion_ = 0;
}
::google::protobuf::int32 CG_LOGIN::gameversion() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.gameversion)
  return gameversion_;
}
void CG_LOGIN::set_gameversion(::google::protobuf::int32 value) {
  
  gameversion_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.gameversion)
}

// int32 programversion = 3;
void CG_LOGIN::clear_programversion() {
  programversion_ = 0;
}
::google::protobuf::int32 CG_LOGIN::programversion() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.programversion)
  return programversion_;
}
void CG_LOGIN::set_programversion(::google::protobuf::int32 value) {
  
  programversion_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.programversion)
}

// int32 publicresourceversion = 4;
void CG_LOGIN::clear_publicresourceversion() {
  publicresourceversion_ = 0;
}
::google::protobuf::int32 CG_LOGIN::publicresourceversion() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.publicresourceversion)
  return publicresourceversion_;
}
void CG_LOGIN::set_publicresourceversion(::google::protobuf::int32 value) {
  
  publicresourceversion_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.publicresourceversion)
}

// int32 maxpacketid = 5;
void CG_LOGIN::clear_maxpacketid() {
  maxpacketid_ = 0;
}
::google::protobuf::int32 CG_LOGIN::maxpacketid() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.maxpacketid)
  return maxpacketid_;
}
void CG_LOGIN::set_maxpacketid(::google::protobuf::int32 value) {
  
  maxpacketid_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.maxpacketid)
}

// int32 forceenter = 6;
void CG_LOGIN::clear_forceenter() {
  forceenter_ = 0;
}
::google::protobuf::int32 CG_LOGIN::forceenter() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.forceenter)
  return forceenter_;
}
void CG_LOGIN::set_forceenter(::google::protobuf::int32 value) {
  
  forceenter_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.forceenter)
}

// string deviceid = 7;
void CG_LOGIN::clear_deviceid() {
  deviceid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::deviceid() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.deviceid)
  return deviceid_.GetNoArena();
}
void CG_LOGIN::set_deviceid(const ::std::string& value) {
  
  deviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.deviceid)
}
#if LANG_CXX11
void CG_LOGIN::set_deviceid(::std::string&& value) {
  
  deviceid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.deviceid)
}
#endif
void CG_LOGIN::set_deviceid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  deviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.deviceid)
}
void CG_LOGIN::set_deviceid(const char* value, size_t size) {
  
  deviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.deviceid)
}
::std::string* CG_LOGIN::mutable_deviceid() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.deviceid)
  return deviceid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_deviceid() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.deviceid)
  
  return deviceid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_deviceid(::std::string* deviceid) {
  if (deviceid != NULL) {
    
  } else {
    
  }
  deviceid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), deviceid);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.deviceid)
}

// string devicetype = 8;
void CG_LOGIN::clear_devicetype() {
  devicetype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::devicetype() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.devicetype)
  return devicetype_.GetNoArena();
}
void CG_LOGIN::set_devicetype(const ::std::string& value) {
  
  devicetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.devicetype)
}
#if LANG_CXX11
void CG_LOGIN::set_devicetype(::std::string&& value) {
  
  devicetype_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.devicetype)
}
#endif
void CG_LOGIN::set_devicetype(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  devicetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.devicetype)
}
void CG_LOGIN::set_devicetype(const char* value, size_t size) {
  
  devicetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.devicetype)
}
::std::string* CG_LOGIN::mutable_devicetype() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.devicetype)
  return devicetype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_devicetype() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.devicetype)
  
  return devicetype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_devicetype(::std::string* devicetype) {
  if (devicetype != NULL) {
    
  } else {
    
  }
  devicetype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), devicetype);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.devicetype)
}

// string deviceversion = 9;
void CG_LOGIN::clear_deviceversion() {
  deviceversion_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::deviceversion() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.deviceversion)
  return deviceversion_.GetNoArena();
}
void CG_LOGIN::set_deviceversion(const ::std::string& value) {
  
  deviceversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.deviceversion)
}
#if LANG_CXX11
void CG_LOGIN::set_deviceversion(::std::string&& value) {
  
  deviceversion_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.deviceversion)
}
#endif
void CG_LOGIN::set_deviceversion(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  deviceversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.deviceversion)
}
void CG_LOGIN::set_deviceversion(const char* value, size_t size) {
  
  deviceversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.deviceversion)
}
::std::string* CG_LOGIN::mutable_deviceversion() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.deviceversion)
  return deviceversion_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_deviceversion() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.deviceversion)
  
  return deviceversion_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_deviceversion(::std::string* deviceversion) {
  if (deviceversion != NULL) {
    
  } else {
    
  }
  deviceversion_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), deviceversion);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.deviceversion)
}

// string account = 10;
void CG_LOGIN::clear_account() {
  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::account() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.account)
  return account_.GetNoArena();
}
void CG_LOGIN::set_account(const ::std::string& value) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.account)
}
#if LANG_CXX11
void CG_LOGIN::set_account(::std::string&& value) {
  
  account_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.account)
}
#endif
void CG_LOGIN::set_account(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.account)
}
void CG_LOGIN::set_account(const char* value, size_t size) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.account)
}
::std::string* CG_LOGIN::mutable_account() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.account)
  return account_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_account() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.account)
  
  return account_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_account(::std::string* account) {
  if (account != NULL) {
    
  } else {
    
  }
  account_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.account)
}

// string validateinfo = 11;
void CG_LOGIN::clear_validateinfo() {
  validateinfo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::validateinfo() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.validateinfo)
  return validateinfo_.GetNoArena();
}
void CG_LOGIN::set_validateinfo(const ::std::string& value) {
  
  validateinfo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.validateinfo)
}
#if LANG_CXX11
void CG_LOGIN::set_validateinfo(::std::string&& value) {
  
  validateinfo_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.validateinfo)
}
#endif
void CG_LOGIN::set_validateinfo(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  validateinfo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.validateinfo)
}
void CG_LOGIN::set_validateinfo(const char* value, size_t size) {
  
  validateinfo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.validateinfo)
}
::std::string* CG_LOGIN::mutable_validateinfo() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.validateinfo)
  return validateinfo_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_validateinfo() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.validateinfo)
  
  return validateinfo_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_validateinfo(::std::string* validateinfo) {
  if (validateinfo != NULL) {
    
  } else {
    
  }
  validateinfo_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), validateinfo);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.validateinfo)
}

// string channelid = 12;
void CG_LOGIN::clear_channelid() {
  channelid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::channelid() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.channelid)
  return channelid_.GetNoArena();
}
void CG_LOGIN::set_channelid(const ::std::string& value) {
  
  channelid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.channelid)
}
#if LANG_CXX11
void CG_LOGIN::set_channelid(::std::string&& value) {
  
  channelid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.channelid)
}
#endif
void CG_LOGIN::set_channelid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  channelid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.channelid)
}
void CG_LOGIN::set_channelid(const char* value, size_t size) {
  
  channelid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.channelid)
}
::std::string* CG_LOGIN::mutable_channelid() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.channelid)
  return channelid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_channelid() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.channelid)
  
  return channelid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_channelid(::std::string* channelid) {
  if (channelid != NULL) {
    
  } else {
    
  }
  channelid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), channelid);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.channelid)
}

// string mediachannel = 13;
void CG_LOGIN::clear_mediachannel() {
  mediachannel_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::mediachannel() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.mediachannel)
  return mediachannel_.GetNoArena();
}
void CG_LOGIN::set_mediachannel(const ::std::string& value) {
  
  mediachannel_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.mediachannel)
}
#if LANG_CXX11
void CG_LOGIN::set_mediachannel(::std::string&& value) {
  
  mediachannel_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.mediachannel)
}
#endif
void CG_LOGIN::set_mediachannel(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  mediachannel_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.mediachannel)
}
void CG_LOGIN::set_mediachannel(const char* value, size_t size) {
  
  mediachannel_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.mediachannel)
}
::std::string* CG_LOGIN::mutable_mediachannel() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.mediachannel)
  return mediachannel_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_mediachannel() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.mediachannel)
  
  return mediachannel_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_mediachannel(::std::string* mediachannel) {
  if (mediachannel != NULL) {
    
  } else {
    
  }
  mediachannel_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mediachannel);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.mediachannel)
}

// int32 rapidvalidatecode = 14;
void CG_LOGIN::clear_rapidvalidatecode() {
  rapidvalidatecode_ = 0;
}
::google::protobuf::int32 CG_LOGIN::rapidvalidatecode() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.rapidvalidatecode)
  return rapidvalidatecode_;
}
void CG_LOGIN::set_rapidvalidatecode(::google::protobuf::int32 value) {
  
  rapidvalidatecode_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.rapidvalidatecode)
}

// int32 reservedint1 = 15;
void CG_LOGIN::clear_reservedint1() {
  reservedint1_ = 0;
}
::google::protobuf::int32 CG_LOGIN::reservedint1() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedint1)
  return reservedint1_;
}
void CG_LOGIN::set_reservedint1(::google::protobuf::int32 value) {
  
  reservedint1_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedint1)
}

// int32 reservedint2 = 16;
void CG_LOGIN::clear_reservedint2() {
  reservedint2_ = 0;
}
::google::protobuf::int32 CG_LOGIN::reservedint2() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedint2)
  return reservedint2_;
}
void CG_LOGIN::set_reservedint2(::google::protobuf::int32 value) {
  
  reservedint2_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedint2)
}

// int32 reservedint3 = 17;
void CG_LOGIN::clear_reservedint3() {
  reservedint3_ = 0;
}
::google::protobuf::int32 CG_LOGIN::reservedint3() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedint3)
  return reservedint3_;
}
void CG_LOGIN::set_reservedint3(::google::protobuf::int32 value) {
  
  reservedint3_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedint3)
}

// int32 reservedint4 = 18;
void CG_LOGIN::clear_reservedint4() {
  reservedint4_ = 0;
}
::google::protobuf::int32 CG_LOGIN::reservedint4() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedint4)
  return reservedint4_;
}
void CG_LOGIN::set_reservedint4(::google::protobuf::int32 value) {
  
  reservedint4_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedint4)
}

// string reservedstring1 = 19;
void CG_LOGIN::clear_reservedstring1() {
  reservedstring1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::reservedstring1() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedstring1)
  return reservedstring1_.GetNoArena();
}
void CG_LOGIN::set_reservedstring1(const ::std::string& value) {
  
  reservedstring1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedstring1)
}
#if LANG_CXX11
void CG_LOGIN::set_reservedstring1(::std::string&& value) {
  
  reservedstring1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.reservedstring1)
}
#endif
void CG_LOGIN::set_reservedstring1(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  reservedstring1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.reservedstring1)
}
void CG_LOGIN::set_reservedstring1(const char* value, size_t size) {
  
  reservedstring1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.reservedstring1)
}
::std::string* CG_LOGIN::mutable_reservedstring1() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.reservedstring1)
  return reservedstring1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_reservedstring1() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.reservedstring1)
  
  return reservedstring1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_reservedstring1(::std::string* reservedstring1) {
  if (reservedstring1 != NULL) {
    
  } else {
    
  }
  reservedstring1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reservedstring1);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.reservedstring1)
}

// string reservedstring2 = 20;
void CG_LOGIN::clear_reservedstring2() {
  reservedstring2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::reservedstring2() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedstring2)
  return reservedstring2_.GetNoArena();
}
void CG_LOGIN::set_reservedstring2(const ::std::string& value) {
  
  reservedstring2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedstring2)
}
#if LANG_CXX11
void CG_LOGIN::set_reservedstring2(::std::string&& value) {
  
  reservedstring2_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.reservedstring2)
}
#endif
void CG_LOGIN::set_reservedstring2(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  reservedstring2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.reservedstring2)
}
void CG_LOGIN::set_reservedstring2(const char* value, size_t size) {
  
  reservedstring2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.reservedstring2)
}
::std::string* CG_LOGIN::mutable_reservedstring2() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.reservedstring2)
  return reservedstring2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_reservedstring2() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.reservedstring2)
  
  return reservedstring2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_reservedstring2(::std::string* reservedstring2) {
  if (reservedstring2 != NULL) {
    
  } else {
    
  }
  reservedstring2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reservedstring2);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.reservedstring2)
}

// string reservedstring3 = 21;
void CG_LOGIN::clear_reservedstring3() {
  reservedstring3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::reservedstring3() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedstring3)
  return reservedstring3_.GetNoArena();
}
void CG_LOGIN::set_reservedstring3(const ::std::string& value) {
  
  reservedstring3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedstring3)
}
#if LANG_CXX11
void CG_LOGIN::set_reservedstring3(::std::string&& value) {
  
  reservedstring3_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.reservedstring3)
}
#endif
void CG_LOGIN::set_reservedstring3(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  reservedstring3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.reservedstring3)
}
void CG_LOGIN::set_reservedstring3(const char* value, size_t size) {
  
  reservedstring3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.reservedstring3)
}
::std::string* CG_LOGIN::mutable_reservedstring3() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.reservedstring3)
  return reservedstring3_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_reservedstring3() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.reservedstring3)
  
  return reservedstring3_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_reservedstring3(::std::string* reservedstring3) {
  if (reservedstring3 != NULL) {
    
  } else {
    
  }
  reservedstring3_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reservedstring3);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.reservedstring3)
}

// string reservedstring4 = 22;
void CG_LOGIN::clear_reservedstring4() {
  reservedstring4_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CG_LOGIN::reservedstring4() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedstring4)
  return reservedstring4_.GetNoArena();
}
void CG_LOGIN::set_reservedstring4(const ::std::string& value) {
  
  reservedstring4_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedstring4)
}
#if LANG_CXX11
void CG_LOGIN::set_reservedstring4(::std::string&& value) {
  
  reservedstring4_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:google.protobuf.CG_LOGIN.reservedstring4)
}
#endif
void CG_LOGIN::set_reservedstring4(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  reservedstring4_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.reservedstring4)
}
void CG_LOGIN::set_reservedstring4(const char* value, size_t size) {
  
  reservedstring4_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.reservedstring4)
}
::std::string* CG_LOGIN::mutable_reservedstring4() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.reservedstring4)
  return reservedstring4_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CG_LOGIN::release_reservedstring4() {
  // @@protoc_insertion_point(field_release:google.protobuf.CG_LOGIN.reservedstring4)
  
  return reservedstring4_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CG_LOGIN::set_allocated_reservedstring4(::std::string* reservedstring4) {
  if (reservedstring4 != NULL) {
    
  } else {
    
  }
  reservedstring4_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reservedstring4);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.reservedstring4)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GC_LOGIN::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GC_LOGIN::GC_LOGIN()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Packet_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.GC_LOGIN)
}
GC_LOGIN::GC_LOGIN(const GC_LOGIN& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:google.protobuf.GC_LOGIN)
}

void GC_LOGIN::SharedCtor() {
  result_ = 0;
  _cached_size_ = 0;
}

GC_LOGIN::~GC_LOGIN() {
  // @@protoc_insertion_point(destructor:google.protobuf.GC_LOGIN)
  SharedDtor();
}

void GC_LOGIN::SharedDtor() {
}

void GC_LOGIN::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GC_LOGIN::descriptor() {
  protobuf_Packet_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Packet_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GC_LOGIN& GC_LOGIN::default_instance() {
  protobuf_Packet_2eproto::InitDefaults();
  return *internal_default_instance();
}

GC_LOGIN* GC_LOGIN::New(::google::protobuf::Arena* arena) const {
  GC_LOGIN* n = new GC_LOGIN;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GC_LOGIN::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.GC_LOGIN)
  result_ = 0;
}

bool GC_LOGIN::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.GC_LOGIN)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 result = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.GC_LOGIN)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.GC_LOGIN)
  return false;
#undef DO_
}

void GC_LOGIN::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.GC_LOGIN)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  // @@protoc_insertion_point(serialize_end:google.protobuf.GC_LOGIN)
}

::google::protobuf::uint8* GC_LOGIN::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.GC_LOGIN)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.GC_LOGIN)
  return target;
}

size_t GC_LOGIN::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.GC_LOGIN)
  size_t total_size = 0;

  // int32 result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GC_LOGIN::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.GC_LOGIN)
  GOOGLE_DCHECK_NE(&from, this);
  const GC_LOGIN* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GC_LOGIN>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.GC_LOGIN)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.GC_LOGIN)
    MergeFrom(*source);
  }
}

void GC_LOGIN::MergeFrom(const GC_LOGIN& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.GC_LOGIN)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.result() != 0) {
    set_result(from.result());
  }
}

void GC_LOGIN::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.GC_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GC_LOGIN::CopyFrom(const GC_LOGIN& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.GC_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GC_LOGIN::IsInitialized() const {
  return true;
}

void GC_LOGIN::Swap(GC_LOGIN* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GC_LOGIN::InternalSwap(GC_LOGIN* other) {
  std::swap(result_, other->result_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GC_LOGIN::GetMetadata() const {
  protobuf_Packet_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Packet_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GC_LOGIN

// int32 result = 1;
void GC_LOGIN::clear_result() {
  result_ = 0;
}
::google::protobuf::int32 GC_LOGIN::result() const {
  // @@protoc_insertion_point(field_get:google.protobuf.GC_LOGIN.result)
  return result_;
}
void GC_LOGIN::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.GC_LOGIN.result)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
