// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Packet.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace google {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* CG_LOGIN_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CG_LOGIN_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* CG_LOGIN_VALIDATETYPE_descriptor_ = NULL;
const ::google::protobuf::Descriptor* GC_LOGIN_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GC_LOGIN_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Packet_2eproto() {
  protobuf_AddDesc_Packet_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Packet.proto");
  GOOGLE_CHECK(file != NULL);
  CG_LOGIN_descriptor_ = file->message_type(0);
  static const int CG_LOGIN_offsets_[22] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, vtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, gameversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, programversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, publicresourceversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, maxpacketid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, forceenter_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, deviceid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, devicetype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, deviceversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, account_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, validateinfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, channelid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, mediachannel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, rapidvalidatecode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedint1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedint2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedint3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedint4_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedstring1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedstring2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedstring3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, reservedstring4_),
  };
  CG_LOGIN_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CG_LOGIN_descriptor_,
      CG_LOGIN::default_instance_,
      CG_LOGIN_offsets_,
      -1,
      -1,
      -1,
      sizeof(CG_LOGIN),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CG_LOGIN, _is_default_instance_));
  CG_LOGIN_VALIDATETYPE_descriptor_ = CG_LOGIN_descriptor_->enum_type(0);
  GC_LOGIN_descriptor_ = file->message_type(1);
  static const int GC_LOGIN_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GC_LOGIN, result_),
  };
  GC_LOGIN_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GC_LOGIN_descriptor_,
      GC_LOGIN::default_instance_,
      GC_LOGIN_offsets_,
      -1,
      -1,
      -1,
      sizeof(GC_LOGIN),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GC_LOGIN, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GC_LOGIN, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Packet_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CG_LOGIN_descriptor_, &CG_LOGIN::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GC_LOGIN_descriptor_, &GC_LOGIN::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Packet_2eproto() {
  delete CG_LOGIN::default_instance_;
  delete CG_LOGIN_reflection_;
  delete GC_LOGIN::default_instance_;
  delete GC_LOGIN_reflection_;
}

void protobuf_AddDesc_Packet_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014Packet.proto\022\017google.protobuf\"\226\004\n\010CG_L"
    "OGIN\022\r\n\005vtype\030\001 \001(\005\022\023\n\013gameversion\030\002 \001(\005"
    "\022\026\n\016programversion\030\003 \001(\005\022\035\n\025publicresour"
    "ceversion\030\004 \001(\005\022\023\n\013maxpacketid\030\005 \001(\005\022\022\n\n"
    "forceenter\030\006 \001(\005\022\020\n\010deviceid\030\007 \001(\t\022\022\n\nde"
    "vicetype\030\010 \001(\t\022\025\n\rdeviceversion\030\t \001(\t\022\017\n"
    "\007account\030\n \001(\t\022\024\n\014validateinfo\030\013 \001(\t\022\021\n\t"
    "channelid\030\014 \001(\t\022\024\n\014mediachannel\030\r \001(\t\022\031\n"
    "\021rapidvalidatecode\030\016 \001(\005\022\024\n\014reservedint1"
    "\030\017 \001(\005\022\024\n\014reservedint2\030\020 \001(\005\022\024\n\014reserved"
    "int3\030\021 \001(\005\022\024\n\014reservedint4\030\022 \001(\005\022\027\n\017rese"
    "rvedstring1\030\023 \001(\t\022\027\n\017reservedstring2\030\024 \001"
    "(\t\022\027\n\017reservedstring3\030\025 \001(\t\022\027\n\017reserveds"
    "tring4\030\026 \001(\t\"\"\n\014VALIDATETYPE\022\010\n\004TEST\020\000\022\010"
    "\n\004CYOU\020\001\"\032\n\010GC_LOGIN\022\016\n\006result\030\001 \001(\005b\006pr"
    "oto3", 604);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Packet.proto", &protobuf_RegisterTypes);
  CG_LOGIN::default_instance_ = new CG_LOGIN();
  GC_LOGIN::default_instance_ = new GC_LOGIN();
  CG_LOGIN::default_instance_->InitAsDefaultInstance();
  GC_LOGIN::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Packet_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Packet_2eproto {
  StaticDescriptorInitializer_Packet_2eproto() {
    protobuf_AddDesc_Packet_2eproto();
  }
} static_descriptor_initializer_Packet_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

const ::google::protobuf::EnumDescriptor* CG_LOGIN_VALIDATETYPE_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CG_LOGIN_VALIDATETYPE_descriptor_;
}
bool CG_LOGIN_VALIDATETYPE_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CG_LOGIN_VALIDATETYPE CG_LOGIN::TEST;
const CG_LOGIN_VALIDATETYPE CG_LOGIN::CYOU;
const CG_LOGIN_VALIDATETYPE CG_LOGIN::VALIDATETYPE_MIN;
const CG_LOGIN_VALIDATETYPE CG_LOGIN::VALIDATETYPE_MAX;
const int CG_LOGIN::VALIDATETYPE_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CG_LOGIN::kVtypeFieldNumber;
const int CG_LOGIN::kGameversionFieldNumber;
const int CG_LOGIN::kProgramversionFieldNumber;
const int CG_LOGIN::kPublicresourceversionFieldNumber;
const int CG_LOGIN::kMaxpacketidFieldNumber;
const int CG_LOGIN::kForceenterFieldNumber;
const int CG_LOGIN::kDeviceidFieldNumber;
const int CG_LOGIN::kDevicetypeFieldNumber;
const int CG_LOGIN::kDeviceversionFieldNumber;
const int CG_LOGIN::kAccountFieldNumber;
const int CG_LOGIN::kValidateinfoFieldNumber;
const int CG_LOGIN::kChannelidFieldNumber;
const int CG_LOGIN::kMediachannelFieldNumber;
const int CG_LOGIN::kRapidvalidatecodeFieldNumber;
const int CG_LOGIN::kReservedint1FieldNumber;
const int CG_LOGIN::kReservedint2FieldNumber;
const int CG_LOGIN::kReservedint3FieldNumber;
const int CG_LOGIN::kReservedint4FieldNumber;
const int CG_LOGIN::kReservedstring1FieldNumber;
const int CG_LOGIN::kReservedstring2FieldNumber;
const int CG_LOGIN::kReservedstring3FieldNumber;
const int CG_LOGIN::kReservedstring4FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CG_LOGIN::CG_LOGIN()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.CG_LOGIN)
}

void CG_LOGIN::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CG_LOGIN::CG_LOGIN(const CG_LOGIN& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:google.protobuf.CG_LOGIN)
}

void CG_LOGIN::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  vtype_ = 0;
  gameversion_ = 0;
  programversion_ = 0;
  publicresourceversion_ = 0;
  maxpacketid_ = 0;
  forceenter_ = 0;
  deviceid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devicetype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deviceversion_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  validateinfo_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channelid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mediachannel_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rapidvalidatecode_ = 0;
  reservedint1_ = 0;
  reservedint2_ = 0;
  reservedint3_ = 0;
  reservedint4_ = 0;
  reservedstring1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring4_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CG_LOGIN::~CG_LOGIN() {
  // @@protoc_insertion_point(destructor:google.protobuf.CG_LOGIN)
  SharedDtor();
}

void CG_LOGIN::SharedDtor() {
  deviceid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devicetype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deviceversion_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  validateinfo_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channelid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mediachannel_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring3_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring4_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void CG_LOGIN::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CG_LOGIN::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CG_LOGIN_descriptor_;
}

const CG_LOGIN& CG_LOGIN::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Packet_2eproto();
  return *default_instance_;
}

CG_LOGIN* CG_LOGIN::default_instance_ = NULL;

CG_LOGIN* CG_LOGIN::New(::google::protobuf::Arena* arena) const {
  CG_LOGIN* n = new CG_LOGIN;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CG_LOGIN::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<CG_LOGIN*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(vtype_, forceenter_);
  deviceid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  devicetype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ZR_(rapidvalidatecode_, reservedint2_);
  deviceversion_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  validateinfo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channelid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mediachannel_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedint3_ = 0;
  reservedint4_ = 0;
  reservedstring1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  reservedstring4_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool CG_LOGIN::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.CG_LOGIN)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(16383);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 vtype = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &vtype_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_gameversion;
        break;
      }

      // optional int32 gameversion = 2;
      case 2: {
        if (tag == 16) {
         parse_gameversion:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &gameversion_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_programversion;
        break;
      }

      // optional int32 programversion = 3;
      case 3: {
        if (tag == 24) {
         parse_programversion:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &programversion_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_publicresourceversion;
        break;
      }

      // optional int32 publicresourceversion = 4;
      case 4: {
        if (tag == 32) {
         parse_publicresourceversion:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &publicresourceversion_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_maxpacketid;
        break;
      }

      // optional int32 maxpacketid = 5;
      case 5: {
        if (tag == 40) {
         parse_maxpacketid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &maxpacketid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_forceenter;
        break;
      }

      // optional int32 forceenter = 6;
      case 6: {
        if (tag == 48) {
         parse_forceenter:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &forceenter_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_deviceid;
        break;
      }

      // optional string deviceid = 7;
      case 7: {
        if (tag == 58) {
         parse_deviceid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deviceid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->deviceid().data(), this->deviceid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.deviceid"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_devicetype;
        break;
      }

      // optional string devicetype = 8;
      case 8: {
        if (tag == 66) {
         parse_devicetype:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_devicetype()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->devicetype().data(), this->devicetype().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.devicetype"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_deviceversion;
        break;
      }

      // optional string deviceversion = 9;
      case 9: {
        if (tag == 74) {
         parse_deviceversion:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deviceversion()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->deviceversion().data(), this->deviceversion().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.deviceversion"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_account;
        break;
      }

      // optional string account = 10;
      case 10: {
        if (tag == 82) {
         parse_account:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_account()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->account().data(), this->account().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.account"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_validateinfo;
        break;
      }

      // optional string validateinfo = 11;
      case 11: {
        if (tag == 90) {
         parse_validateinfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_validateinfo()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->validateinfo().data(), this->validateinfo().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.validateinfo"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_channelid;
        break;
      }

      // optional string channelid = 12;
      case 12: {
        if (tag == 98) {
         parse_channelid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_channelid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->channelid().data(), this->channelid().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.channelid"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(106)) goto parse_mediachannel;
        break;
      }

      // optional string mediachannel = 13;
      case 13: {
        if (tag == 106) {
         parse_mediachannel:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mediachannel()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->mediachannel().data(), this->mediachannel().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.mediachannel"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(112)) goto parse_rapidvalidatecode;
        break;
      }

      // optional int32 rapidvalidatecode = 14;
      case 14: {
        if (tag == 112) {
         parse_rapidvalidatecode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rapidvalidatecode_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(120)) goto parse_reservedint1;
        break;
      }

      // optional int32 reservedint1 = 15;
      case 15: {
        if (tag == 120) {
         parse_reservedint1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reservedint1_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(128)) goto parse_reservedint2;
        break;
      }

      // optional int32 reservedint2 = 16;
      case 16: {
        if (tag == 128) {
         parse_reservedint2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reservedint2_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(136)) goto parse_reservedint3;
        break;
      }

      // optional int32 reservedint3 = 17;
      case 17: {
        if (tag == 136) {
         parse_reservedint3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reservedint3_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(144)) goto parse_reservedint4;
        break;
      }

      // optional int32 reservedint4 = 18;
      case 18: {
        if (tag == 144) {
         parse_reservedint4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reservedint4_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(154)) goto parse_reservedstring1;
        break;
      }

      // optional string reservedstring1 = 19;
      case 19: {
        if (tag == 154) {
         parse_reservedstring1:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reservedstring1()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->reservedstring1().data(), this->reservedstring1().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.reservedstring1"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(162)) goto parse_reservedstring2;
        break;
      }

      // optional string reservedstring2 = 20;
      case 20: {
        if (tag == 162) {
         parse_reservedstring2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reservedstring2()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->reservedstring2().data(), this->reservedstring2().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.reservedstring2"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(170)) goto parse_reservedstring3;
        break;
      }

      // optional string reservedstring3 = 21;
      case 21: {
        if (tag == 170) {
         parse_reservedstring3:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reservedstring3()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->reservedstring3().data(), this->reservedstring3().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.reservedstring3"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(178)) goto parse_reservedstring4;
        break;
      }

      // optional string reservedstring4 = 22;
      case 22: {
        if (tag == 178) {
         parse_reservedstring4:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_reservedstring4()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->reservedstring4().data(), this->reservedstring4().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.CG_LOGIN.reservedstring4"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.CG_LOGIN)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.CG_LOGIN)
  return false;
#undef DO_
}

void CG_LOGIN::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.CG_LOGIN)
  // optional int32 vtype = 1;
  if (this->vtype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->vtype(), output);
  }

  // optional int32 gameversion = 2;
  if (this->gameversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->gameversion(), output);
  }

  // optional int32 programversion = 3;
  if (this->programversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->programversion(), output);
  }

  // optional int32 publicresourceversion = 4;
  if (this->publicresourceversion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->publicresourceversion(), output);
  }

  // optional int32 maxpacketid = 5;
  if (this->maxpacketid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->maxpacketid(), output);
  }

  // optional int32 forceenter = 6;
  if (this->forceenter() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->forceenter(), output);
  }

  // optional string deviceid = 7;
  if (this->deviceid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deviceid().data(), this->deviceid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.deviceid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->deviceid(), output);
  }

  // optional string devicetype = 8;
  if (this->devicetype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->devicetype().data(), this->devicetype().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.devicetype");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->devicetype(), output);
  }

  // optional string deviceversion = 9;
  if (this->deviceversion().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deviceversion().data(), this->deviceversion().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.deviceversion");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->deviceversion(), output);
  }

  // optional string account = 10;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), this->account().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.account");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->account(), output);
  }

  // optional string validateinfo = 11;
  if (this->validateinfo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->validateinfo().data(), this->validateinfo().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.validateinfo");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->validateinfo(), output);
  }

  // optional string channelid = 12;
  if (this->channelid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channelid().data(), this->channelid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.channelid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->channelid(), output);
  }

  // optional string mediachannel = 13;
  if (this->mediachannel().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mediachannel().data(), this->mediachannel().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.mediachannel");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      13, this->mediachannel(), output);
  }

  // optional int32 rapidvalidatecode = 14;
  if (this->rapidvalidatecode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(14, this->rapidvalidatecode(), output);
  }

  // optional int32 reservedint1 = 15;
  if (this->reservedint1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(15, this->reservedint1(), output);
  }

  // optional int32 reservedint2 = 16;
  if (this->reservedint2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(16, this->reservedint2(), output);
  }

  // optional int32 reservedint3 = 17;
  if (this->reservedint3() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(17, this->reservedint3(), output);
  }

  // optional int32 reservedint4 = 18;
  if (this->reservedint4() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(18, this->reservedint4(), output);
  }

  // optional string reservedstring1 = 19;
  if (this->reservedstring1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring1().data(), this->reservedstring1().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      19, this->reservedstring1(), output);
  }

  // optional string reservedstring2 = 20;
  if (this->reservedstring2().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring2().data(), this->reservedstring2().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      20, this->reservedstring2(), output);
  }

  // optional string reservedstring3 = 21;
  if (this->reservedstring3().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring3().data(), this->reservedstring3().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring3");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      21, this->reservedstring3(), output);
  }

  // optional string reservedstring4 = 22;
  if (this->reservedstring4().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring4().data(), this->reservedstring4().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring4");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      22, this->reservedstring4(), output);
  }

  // @@protoc_insertion_point(serialize_end:google.protobuf.CG_LOGIN)
}

::google::protobuf::uint8* CG_LOGIN::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.CG_LOGIN)
  // optional int32 vtype = 1;
  if (this->vtype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->vtype(), target);
  }

  // optional int32 gameversion = 2;
  if (this->gameversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->gameversion(), target);
  }

  // optional int32 programversion = 3;
  if (this->programversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->programversion(), target);
  }

  // optional int32 publicresourceversion = 4;
  if (this->publicresourceversion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->publicresourceversion(), target);
  }

  // optional int32 maxpacketid = 5;
  if (this->maxpacketid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->maxpacketid(), target);
  }

  // optional int32 forceenter = 6;
  if (this->forceenter() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->forceenter(), target);
  }

  // optional string deviceid = 7;
  if (this->deviceid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deviceid().data(), this->deviceid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.deviceid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->deviceid(), target);
  }

  // optional string devicetype = 8;
  if (this->devicetype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->devicetype().data(), this->devicetype().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.devicetype");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->devicetype(), target);
  }

  // optional string deviceversion = 9;
  if (this->deviceversion().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deviceversion().data(), this->deviceversion().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.deviceversion");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->deviceversion(), target);
  }

  // optional string account = 10;
  if (this->account().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->account().data(), this->account().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.account");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->account(), target);
  }

  // optional string validateinfo = 11;
  if (this->validateinfo().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->validateinfo().data(), this->validateinfo().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.validateinfo");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->validateinfo(), target);
  }

  // optional string channelid = 12;
  if (this->channelid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->channelid().data(), this->channelid().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.channelid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->channelid(), target);
  }

  // optional string mediachannel = 13;
  if (this->mediachannel().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mediachannel().data(), this->mediachannel().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.mediachannel");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        13, this->mediachannel(), target);
  }

  // optional int32 rapidvalidatecode = 14;
  if (this->rapidvalidatecode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(14, this->rapidvalidatecode(), target);
  }

  // optional int32 reservedint1 = 15;
  if (this->reservedint1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(15, this->reservedint1(), target);
  }

  // optional int32 reservedint2 = 16;
  if (this->reservedint2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(16, this->reservedint2(), target);
  }

  // optional int32 reservedint3 = 17;
  if (this->reservedint3() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(17, this->reservedint3(), target);
  }

  // optional int32 reservedint4 = 18;
  if (this->reservedint4() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(18, this->reservedint4(), target);
  }

  // optional string reservedstring1 = 19;
  if (this->reservedstring1().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring1().data(), this->reservedstring1().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        19, this->reservedstring1(), target);
  }

  // optional string reservedstring2 = 20;
  if (this->reservedstring2().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring2().data(), this->reservedstring2().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        20, this->reservedstring2(), target);
  }

  // optional string reservedstring3 = 21;
  if (this->reservedstring3().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring3().data(), this->reservedstring3().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring3");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        21, this->reservedstring3(), target);
  }

  // optional string reservedstring4 = 22;
  if (this->reservedstring4().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->reservedstring4().data(), this->reservedstring4().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.CG_LOGIN.reservedstring4");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        22, this->reservedstring4(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.CG_LOGIN)
  return target;
}

int CG_LOGIN::ByteSize() const {
  int total_size = 0;

  // optional int32 vtype = 1;
  if (this->vtype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->vtype());
  }

  // optional int32 gameversion = 2;
  if (this->gameversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->gameversion());
  }

  // optional int32 programversion = 3;
  if (this->programversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->programversion());
  }

  // optional int32 publicresourceversion = 4;
  if (this->publicresourceversion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->publicresourceversion());
  }

  // optional int32 maxpacketid = 5;
  if (this->maxpacketid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->maxpacketid());
  }

  // optional int32 forceenter = 6;
  if (this->forceenter() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->forceenter());
  }

  // optional string deviceid = 7;
  if (this->deviceid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->deviceid());
  }

  // optional string devicetype = 8;
  if (this->devicetype().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->devicetype());
  }

  // optional string deviceversion = 9;
  if (this->deviceversion().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->deviceversion());
  }

  // optional string account = 10;
  if (this->account().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->account());
  }

  // optional string validateinfo = 11;
  if (this->validateinfo().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->validateinfo());
  }

  // optional string channelid = 12;
  if (this->channelid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->channelid());
  }

  // optional string mediachannel = 13;
  if (this->mediachannel().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mediachannel());
  }

  // optional int32 rapidvalidatecode = 14;
  if (this->rapidvalidatecode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rapidvalidatecode());
  }

  // optional int32 reservedint1 = 15;
  if (this->reservedint1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reservedint1());
  }

  // optional int32 reservedint2 = 16;
  if (this->reservedint2() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reservedint2());
  }

  // optional int32 reservedint3 = 17;
  if (this->reservedint3() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reservedint3());
  }

  // optional int32 reservedint4 = 18;
  if (this->reservedint4() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reservedint4());
  }

  // optional string reservedstring1 = 19;
  if (this->reservedstring1().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reservedstring1());
  }

  // optional string reservedstring2 = 20;
  if (this->reservedstring2().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reservedstring2());
  }

  // optional string reservedstring3 = 21;
  if (this->reservedstring3().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reservedstring3());
  }

  // optional string reservedstring4 = 22;
  if (this->reservedstring4().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->reservedstring4());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CG_LOGIN::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CG_LOGIN* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CG_LOGIN>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CG_LOGIN::MergeFrom(const CG_LOGIN& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.vtype() != 0) {
    set_vtype(from.vtype());
  }
  if (from.gameversion() != 0) {
    set_gameversion(from.gameversion());
  }
  if (from.programversion() != 0) {
    set_programversion(from.programversion());
  }
  if (from.publicresourceversion() != 0) {
    set_publicresourceversion(from.publicresourceversion());
  }
  if (from.maxpacketid() != 0) {
    set_maxpacketid(from.maxpacketid());
  }
  if (from.forceenter() != 0) {
    set_forceenter(from.forceenter());
  }
  if (from.deviceid().size() > 0) {

    deviceid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deviceid_);
  }
  if (from.devicetype().size() > 0) {

    devicetype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.devicetype_);
  }
  if (from.deviceversion().size() > 0) {

    deviceversion_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deviceversion_);
  }
  if (from.account().size() > 0) {

    account_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.account_);
  }
  if (from.validateinfo().size() > 0) {

    validateinfo_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.validateinfo_);
  }
  if (from.channelid().size() > 0) {

    channelid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.channelid_);
  }
  if (from.mediachannel().size() > 0) {

    mediachannel_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mediachannel_);
  }
  if (from.rapidvalidatecode() != 0) {
    set_rapidvalidatecode(from.rapidvalidatecode());
  }
  if (from.reservedint1() != 0) {
    set_reservedint1(from.reservedint1());
  }
  if (from.reservedint2() != 0) {
    set_reservedint2(from.reservedint2());
  }
  if (from.reservedint3() != 0) {
    set_reservedint3(from.reservedint3());
  }
  if (from.reservedint4() != 0) {
    set_reservedint4(from.reservedint4());
  }
  if (from.reservedstring1().size() > 0) {

    reservedstring1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring1_);
  }
  if (from.reservedstring2().size() > 0) {

    reservedstring2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring2_);
  }
  if (from.reservedstring3().size() > 0) {

    reservedstring3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring3_);
  }
  if (from.reservedstring4().size() > 0) {

    reservedstring4_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.reservedstring4_);
  }
}

void CG_LOGIN::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CG_LOGIN::CopyFrom(const CG_LOGIN& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CG_LOGIN::IsInitialized() const {

  return true;
}

void CG_LOGIN::Swap(CG_LOGIN* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CG_LOGIN::InternalSwap(CG_LOGIN* other) {
  std::swap(vtype_, other->vtype_);
  std::swap(gameversion_, other->gameversion_);
  std::swap(programversion_, other->programversion_);
  std::swap(publicresourceversion_, other->publicresourceversion_);
  std::swap(maxpacketid_, other->maxpacketid_);
  std::swap(forceenter_, other->forceenter_);
  deviceid_.Swap(&other->deviceid_);
  devicetype_.Swap(&other->devicetype_);
  deviceversion_.Swap(&other->deviceversion_);
  account_.Swap(&other->account_);
  validateinfo_.Swap(&other->validateinfo_);
  channelid_.Swap(&other->channelid_);
  mediachannel_.Swap(&other->mediachannel_);
  std::swap(rapidvalidatecode_, other->rapidvalidatecode_);
  std::swap(reservedint1_, other->reservedint1_);
  std::swap(reservedint2_, other->reservedint2_);
  std::swap(reservedint3_, other->reservedint3_);
  std::swap(reservedint4_, other->reservedint4_);
  reservedstring1_.Swap(&other->reservedstring1_);
  reservedstring2_.Swap(&other->reservedstring2_);
  reservedstring3_.Swap(&other->reservedstring3_);
  reservedstring4_.Swap(&other->reservedstring4_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CG_LOGIN::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CG_LOGIN_descriptor_;
  metadata.reflection = CG_LOGIN_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CG_LOGIN

// optional int32 vtype = 1;
void CG_LOGIN::clear_vtype() {
  vtype_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::vtype() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.vtype)
  return vtype_;
}
 void CG_LOGIN::set_vtype(::google::protobuf::int32 value) {
  
  vtype_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.vtype)
}

// optional int32 gameversion = 2;
void CG_LOGIN::clear_gameversion() {
  gameversion_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::gameversion() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.gameversion)
  return gameversion_;
}
 void CG_LOGIN::set_gameversion(::google::protobuf::int32 value) {
  
  gameversion_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.gameversion)
}

// optional int32 programversion = 3;
void CG_LOGIN::clear_programversion() {
  programversion_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::programversion() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.programversion)
  return programversion_;
}
 void CG_LOGIN::set_programversion(::google::protobuf::int32 value) {
  
  programversion_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.programversion)
}

// optional int32 publicresourceversion = 4;
void CG_LOGIN::clear_publicresourceversion() {
  publicresourceversion_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::publicresourceversion() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.publicresourceversion)
  return publicresourceversion_;
}
 void CG_LOGIN::set_publicresourceversion(::google::protobuf::int32 value) {
  
  publicresourceversion_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.publicresourceversion)
}

// optional int32 maxpacketid = 5;
void CG_LOGIN::clear_maxpacketid() {
  maxpacketid_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::maxpacketid() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.maxpacketid)
  return maxpacketid_;
}
 void CG_LOGIN::set_maxpacketid(::google::protobuf::int32 value) {
  
  maxpacketid_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.maxpacketid)
}

// optional int32 forceenter = 6;
void CG_LOGIN::clear_forceenter() {
  forceenter_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::forceenter() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.forceenter)
  return forceenter_;
}
 void CG_LOGIN::set_forceenter(::google::protobuf::int32 value) {
  
  forceenter_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.forceenter)
}

// optional string deviceid = 7;
void CG_LOGIN::clear_deviceid() {
  deviceid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::deviceid() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.deviceid)
  return deviceid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_deviceid(const ::std::string& value) {
  
  deviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.deviceid)
}
 void CG_LOGIN::set_deviceid(const char* value) {
  
  deviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.deviceid)
}
 void CG_LOGIN::set_deviceid(const char* value, size_t size) {
  
  deviceid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.deviceid)
}
 ::std::string* CG_LOGIN::mutable_deviceid() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.deviceid)
  return deviceid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_deviceid() {
  
  return deviceid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_deviceid(::std::string* deviceid) {
  if (deviceid != NULL) {
    
  } else {
    
  }
  deviceid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), deviceid);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.deviceid)
}

// optional string devicetype = 8;
void CG_LOGIN::clear_devicetype() {
  devicetype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::devicetype() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.devicetype)
  return devicetype_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_devicetype(const ::std::string& value) {
  
  devicetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.devicetype)
}
 void CG_LOGIN::set_devicetype(const char* value) {
  
  devicetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.devicetype)
}
 void CG_LOGIN::set_devicetype(const char* value, size_t size) {
  
  devicetype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.devicetype)
}
 ::std::string* CG_LOGIN::mutable_devicetype() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.devicetype)
  return devicetype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_devicetype() {
  
  return devicetype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_devicetype(::std::string* devicetype) {
  if (devicetype != NULL) {
    
  } else {
    
  }
  devicetype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), devicetype);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.devicetype)
}

// optional string deviceversion = 9;
void CG_LOGIN::clear_deviceversion() {
  deviceversion_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::deviceversion() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.deviceversion)
  return deviceversion_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_deviceversion(const ::std::string& value) {
  
  deviceversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.deviceversion)
}
 void CG_LOGIN::set_deviceversion(const char* value) {
  
  deviceversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.deviceversion)
}
 void CG_LOGIN::set_deviceversion(const char* value, size_t size) {
  
  deviceversion_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.deviceversion)
}
 ::std::string* CG_LOGIN::mutable_deviceversion() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.deviceversion)
  return deviceversion_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_deviceversion() {
  
  return deviceversion_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_deviceversion(::std::string* deviceversion) {
  if (deviceversion != NULL) {
    
  } else {
    
  }
  deviceversion_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), deviceversion);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.deviceversion)
}

// optional string account = 10;
void CG_LOGIN::clear_account() {
  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::account() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.account)
  return account_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_account(const ::std::string& value) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.account)
}
 void CG_LOGIN::set_account(const char* value) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.account)
}
 void CG_LOGIN::set_account(const char* value, size_t size) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.account)
}
 ::std::string* CG_LOGIN::mutable_account() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.account)
  return account_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_account() {
  
  return account_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_account(::std::string* account) {
  if (account != NULL) {
    
  } else {
    
  }
  account_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.account)
}

// optional string validateinfo = 11;
void CG_LOGIN::clear_validateinfo() {
  validateinfo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::validateinfo() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.validateinfo)
  return validateinfo_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_validateinfo(const ::std::string& value) {
  
  validateinfo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.validateinfo)
}
 void CG_LOGIN::set_validateinfo(const char* value) {
  
  validateinfo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.validateinfo)
}
 void CG_LOGIN::set_validateinfo(const char* value, size_t size) {
  
  validateinfo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.validateinfo)
}
 ::std::string* CG_LOGIN::mutable_validateinfo() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.validateinfo)
  return validateinfo_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_validateinfo() {
  
  return validateinfo_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_validateinfo(::std::string* validateinfo) {
  if (validateinfo != NULL) {
    
  } else {
    
  }
  validateinfo_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), validateinfo);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.validateinfo)
}

// optional string channelid = 12;
void CG_LOGIN::clear_channelid() {
  channelid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::channelid() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.channelid)
  return channelid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_channelid(const ::std::string& value) {
  
  channelid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.channelid)
}
 void CG_LOGIN::set_channelid(const char* value) {
  
  channelid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.channelid)
}
 void CG_LOGIN::set_channelid(const char* value, size_t size) {
  
  channelid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.channelid)
}
 ::std::string* CG_LOGIN::mutable_channelid() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.channelid)
  return channelid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_channelid() {
  
  return channelid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_channelid(::std::string* channelid) {
  if (channelid != NULL) {
    
  } else {
    
  }
  channelid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), channelid);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.channelid)
}

// optional string mediachannel = 13;
void CG_LOGIN::clear_mediachannel() {
  mediachannel_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::mediachannel() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.mediachannel)
  return mediachannel_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_mediachannel(const ::std::string& value) {
  
  mediachannel_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.mediachannel)
}
 void CG_LOGIN::set_mediachannel(const char* value) {
  
  mediachannel_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.mediachannel)
}
 void CG_LOGIN::set_mediachannel(const char* value, size_t size) {
  
  mediachannel_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.mediachannel)
}
 ::std::string* CG_LOGIN::mutable_mediachannel() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.mediachannel)
  return mediachannel_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_mediachannel() {
  
  return mediachannel_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_mediachannel(::std::string* mediachannel) {
  if (mediachannel != NULL) {
    
  } else {
    
  }
  mediachannel_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mediachannel);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.mediachannel)
}

// optional int32 rapidvalidatecode = 14;
void CG_LOGIN::clear_rapidvalidatecode() {
  rapidvalidatecode_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::rapidvalidatecode() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.rapidvalidatecode)
  return rapidvalidatecode_;
}
 void CG_LOGIN::set_rapidvalidatecode(::google::protobuf::int32 value) {
  
  rapidvalidatecode_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.rapidvalidatecode)
}

// optional int32 reservedint1 = 15;
void CG_LOGIN::clear_reservedint1() {
  reservedint1_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::reservedint1() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedint1)
  return reservedint1_;
}
 void CG_LOGIN::set_reservedint1(::google::protobuf::int32 value) {
  
  reservedint1_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedint1)
}

// optional int32 reservedint2 = 16;
void CG_LOGIN::clear_reservedint2() {
  reservedint2_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::reservedint2() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedint2)
  return reservedint2_;
}
 void CG_LOGIN::set_reservedint2(::google::protobuf::int32 value) {
  
  reservedint2_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedint2)
}

// optional int32 reservedint3 = 17;
void CG_LOGIN::clear_reservedint3() {
  reservedint3_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::reservedint3() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedint3)
  return reservedint3_;
}
 void CG_LOGIN::set_reservedint3(::google::protobuf::int32 value) {
  
  reservedint3_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedint3)
}

// optional int32 reservedint4 = 18;
void CG_LOGIN::clear_reservedint4() {
  reservedint4_ = 0;
}
 ::google::protobuf::int32 CG_LOGIN::reservedint4() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedint4)
  return reservedint4_;
}
 void CG_LOGIN::set_reservedint4(::google::protobuf::int32 value) {
  
  reservedint4_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedint4)
}

// optional string reservedstring1 = 19;
void CG_LOGIN::clear_reservedstring1() {
  reservedstring1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::reservedstring1() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedstring1)
  return reservedstring1_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_reservedstring1(const ::std::string& value) {
  
  reservedstring1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedstring1)
}
 void CG_LOGIN::set_reservedstring1(const char* value) {
  
  reservedstring1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.reservedstring1)
}
 void CG_LOGIN::set_reservedstring1(const char* value, size_t size) {
  
  reservedstring1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.reservedstring1)
}
 ::std::string* CG_LOGIN::mutable_reservedstring1() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.reservedstring1)
  return reservedstring1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_reservedstring1() {
  
  return reservedstring1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_reservedstring1(::std::string* reservedstring1) {
  if (reservedstring1 != NULL) {
    
  } else {
    
  }
  reservedstring1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reservedstring1);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.reservedstring1)
}

// optional string reservedstring2 = 20;
void CG_LOGIN::clear_reservedstring2() {
  reservedstring2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::reservedstring2() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedstring2)
  return reservedstring2_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_reservedstring2(const ::std::string& value) {
  
  reservedstring2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedstring2)
}
 void CG_LOGIN::set_reservedstring2(const char* value) {
  
  reservedstring2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.reservedstring2)
}
 void CG_LOGIN::set_reservedstring2(const char* value, size_t size) {
  
  reservedstring2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.reservedstring2)
}
 ::std::string* CG_LOGIN::mutable_reservedstring2() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.reservedstring2)
  return reservedstring2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_reservedstring2() {
  
  return reservedstring2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_reservedstring2(::std::string* reservedstring2) {
  if (reservedstring2 != NULL) {
    
  } else {
    
  }
  reservedstring2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reservedstring2);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.reservedstring2)
}

// optional string reservedstring3 = 21;
void CG_LOGIN::clear_reservedstring3() {
  reservedstring3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::reservedstring3() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedstring3)
  return reservedstring3_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_reservedstring3(const ::std::string& value) {
  
  reservedstring3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedstring3)
}
 void CG_LOGIN::set_reservedstring3(const char* value) {
  
  reservedstring3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.reservedstring3)
}
 void CG_LOGIN::set_reservedstring3(const char* value, size_t size) {
  
  reservedstring3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.reservedstring3)
}
 ::std::string* CG_LOGIN::mutable_reservedstring3() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.reservedstring3)
  return reservedstring3_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_reservedstring3() {
  
  return reservedstring3_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_reservedstring3(::std::string* reservedstring3) {
  if (reservedstring3 != NULL) {
    
  } else {
    
  }
  reservedstring3_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reservedstring3);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.reservedstring3)
}

// optional string reservedstring4 = 22;
void CG_LOGIN::clear_reservedstring4() {
  reservedstring4_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& CG_LOGIN::reservedstring4() const {
  // @@protoc_insertion_point(field_get:google.protobuf.CG_LOGIN.reservedstring4)
  return reservedstring4_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_reservedstring4(const ::std::string& value) {
  
  reservedstring4_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.CG_LOGIN.reservedstring4)
}
 void CG_LOGIN::set_reservedstring4(const char* value) {
  
  reservedstring4_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.CG_LOGIN.reservedstring4)
}
 void CG_LOGIN::set_reservedstring4(const char* value, size_t size) {
  
  reservedstring4_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.CG_LOGIN.reservedstring4)
}
 ::std::string* CG_LOGIN::mutable_reservedstring4() {
  
  // @@protoc_insertion_point(field_mutable:google.protobuf.CG_LOGIN.reservedstring4)
  return reservedstring4_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* CG_LOGIN::release_reservedstring4() {
  
  return reservedstring4_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CG_LOGIN::set_allocated_reservedstring4(::std::string* reservedstring4) {
  if (reservedstring4 != NULL) {
    
  } else {
    
  }
  reservedstring4_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), reservedstring4);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.CG_LOGIN.reservedstring4)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GC_LOGIN::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GC_LOGIN::GC_LOGIN()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.GC_LOGIN)
}

void GC_LOGIN::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GC_LOGIN::GC_LOGIN(const GC_LOGIN& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:google.protobuf.GC_LOGIN)
}

void GC_LOGIN::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  result_ = 0;
}

GC_LOGIN::~GC_LOGIN() {
  // @@protoc_insertion_point(destructor:google.protobuf.GC_LOGIN)
  SharedDtor();
}

void GC_LOGIN::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GC_LOGIN::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GC_LOGIN::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GC_LOGIN_descriptor_;
}

const GC_LOGIN& GC_LOGIN::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Packet_2eproto();
  return *default_instance_;
}

GC_LOGIN* GC_LOGIN::default_instance_ = NULL;

GC_LOGIN* GC_LOGIN::New(::google::protobuf::Arena* arena) const {
  GC_LOGIN* n = new GC_LOGIN;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GC_LOGIN::Clear() {
  result_ = 0;
}

bool GC_LOGIN::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.GC_LOGIN)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 result = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.GC_LOGIN)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.GC_LOGIN)
  return false;
#undef DO_
}

void GC_LOGIN::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.GC_LOGIN)
  // optional int32 result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  // @@protoc_insertion_point(serialize_end:google.protobuf.GC_LOGIN)
}

::google::protobuf::uint8* GC_LOGIN::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.GC_LOGIN)
  // optional int32 result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.GC_LOGIN)
  return target;
}

int GC_LOGIN::ByteSize() const {
  int total_size = 0;

  // optional int32 result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GC_LOGIN::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const GC_LOGIN* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const GC_LOGIN>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GC_LOGIN::MergeFrom(const GC_LOGIN& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.result() != 0) {
    set_result(from.result());
  }
}

void GC_LOGIN::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GC_LOGIN::CopyFrom(const GC_LOGIN& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GC_LOGIN::IsInitialized() const {

  return true;
}

void GC_LOGIN::Swap(GC_LOGIN* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GC_LOGIN::InternalSwap(GC_LOGIN* other) {
  std::swap(result_, other->result_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GC_LOGIN::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GC_LOGIN_descriptor_;
  metadata.reflection = GC_LOGIN_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GC_LOGIN

// optional int32 result = 1;
void GC_LOGIN::clear_result() {
  result_ = 0;
}
 ::google::protobuf::int32 GC_LOGIN::result() const {
  // @@protoc_insertion_point(field_get:google.protobuf.GC_LOGIN.result)
  return result_;
}
 void GC_LOGIN::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.GC_LOGIN.result)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
